/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.11.0
 *
 * Project: 'I2C_FRAM.debug_GCC+NUCLEO-C562RE' 
 * Target:  'debug_GCC+NUCLEO-C562RE' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* STMicroelectronics::Device:STM32CubeMX2 Config:CORE@2.1.0 */
#define USE_ASSERT_DBG_PARAM
          #define USE_ASSERT_DBG_STATE


#endif /* PRE_INCLUDE_GLOBAL_H */
